Project biztrek

Table users {
  id int [pk]
  first_name string
  last_name string
  email string
  password string
  is_admin boolean
  is_mentor boolean
  is_student boolean
  created_at datetime
}

Table courses {
  id int [pk]
  title string
  sub_title string
  price int
  description text
  created_at datetime
  user_id int [ref: > users.id]
}

Table messages {
  id int [pk]
  mentor_id int
  message text
  created_at datetime
}

Table mentors {
  id int [pk]
  description text
  expertise string
  business string
  industry string
  created_at datetime
  user_id int [ref: - users.id]
}

Table carts {
  id int [pk]
  user_id int [ref: - users.id]
  
}


Table carts_courses {
  id int [pk]
  course_id int [ref: > courses.id]
  cart_id int [ref: > carts.id]
}

Table categories {
  id int [pk]
  name string
}

Table courses_categories {
  id int [pk]
  course_id int [ref: > courses.id]
  category_id int [ref: > categories.id]
}

Table wishlists {
  id int [pk]
  user_id int
  quantity int
}

Table testimonials {
  id int [pk]
  user_id int [ref: > users.id]
  course_id int [ref: > courses.id]
  description text
}

Table orders {
  id int [pk]
  user_id int [ref: > users.id]
  course_id int [ref: > courses.id]
}

Table testimonials_ratings_card {
  testimonial_id int
  rating_id int
}

Table ratings {
  id int [pk]
  user_id int
  rating float
}

